#!/bin/bash

pushd dockers/mxe-lnx32
docker build -t safelists_build_env:v1 -f Dockerfile ../../
popd

pushd dockers/rust-musl-lnx32
docker build -t intermediate_rust_musl:v1 -f Dockerfile ../../
popd

pushd dockers/templatious
docker build -t safelists_templatious:v1 .
popd
